apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: atmosphere
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: atmosphere
    spec:
      containers:
      - name: atmosphere
        image: jocatalin/atmosphere:2017
    
